title: CSS 参考手册
description: 免费的 CSS 常见属性视觉指南
share: "CSS Reference: 免费的 CSS 常见属性视觉指南。"
url: http://localhost:4000
markdown: kramdown
permalink: pretty
exclude: ['node_modules']
gems:
  - octopress-autoprefixer
